# Generated by Django 4.1.7 on 2023-02-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_Name', models.CharField(max_length=255)),
                ('your_Name', models.CharField(max_length=255)),
                ('your_employee_Id', models.SmallIntegerField(default=None)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time_taken', models.IntegerField()),
            ],
        ),
    ]
