# Generated by Django 4.1.7 on 2023-02-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheetsApp', '0002_alter_timesheettable_your_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheettable',
            old_name='time_taken',
            new_name='days_taken_to_finish',
        ),
        migrations.AlterField(
            model_name='timesheettable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
