# Generated by Django 4.1.7 on 2023-02-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeSheetsApp', '0003_rename_time_taken_timesheettable_days_taken_to_finish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheettable',
            old_name='days_taken_to_finish',
            new_name='hours_to_finish',
        ),
    ]
